name: Listen dummy-ci status

on:
  status:
  # workflow_run:
    # workflows: ["Dummy CI"]
    # types:
      # - completed

jobs:
  react:
    runs-on: ubuntu-latest

    steps:
      - name: Report result
        run: |
          echo "${{ github.event_name}}"
