name: Supervisor for CI

on:
  check_run:
    types: [completed]

jobs:
  only-for-ci:
    if: ${{ github.event.check_run.name == 'check-updater' && github.event.check_run.pull_requests[0] }}
    runs-on: ubuntu-latest
    steps:
      - name: Reacting to check_run from PR
        run: |
          echo "CI завершён в PR #${{ github.event.check_run.pull_requests[0].number }}"
          echo "Результат: ${{ github.event.check_run.conclusion }}"