name: Dummy CI
on: pull_request

permissions:
  statuses: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish status
        uses: actions/github-script@v7
        env:
          PAT_ACTION: ${{ secrets.PAT_ACTION }}      # ← получили из Secrets
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              sha:   github.event.pull_request.head.sha,
              state: "success",
              context: "Custom status: passed",
              description: "Success",
              headers: { authorization: `token ${process.env.PAT_ACTION}` }
            })
