name: Dummy CI

on:                                # запускаем при любом обновлении PR
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fake build
        run: echo "Hello from CI – I am doing nothing, just pretending!"

      # ----- Публикуем STATUS «success» -----
      - name: Publish SUCCESS status
        if: success()              # выполнится только если всё ↑ прошло
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              sha:   context.sha,
              state: "success",          // <-- статус
              context: "dummy-ci",       // <-- имя «галочки» в PR
              description: "Dummy CI passed 🎉",
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })

      # ----- Публикуем STATUS «failure» -----
      - name: Publish FAILURE status
        if: failure()              # выполнится ТОЛЬКО если что-то упало выше
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              sha:   context.sha,
              state: "failure",
              context: "dummy-ci",
              description: "Dummy CI failed 💥",
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })
