name: Dummy CI
on: pull_request

permissions:
  statuses: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_ACTION }}   # PAT with repo:status
          script: |
            const sha = context.payload.pull_request.head.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              sha,
              state: 'success',
              context: 'Custom status: passed',
              description: 'Success'
            });
