name: Dummy CI
on: pull_request

permissions:
  statuses: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from CI"

      - name: Publish SUCCESS status
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              sha:   context.sha,
              state: "success",
              context: "dummy-ci",
              description: "Dummy CI passed",
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })
